version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - "message_service"
      - "user_service"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - "api-network"

  message_service:
    build: "./message_service"
    ports:
      - "10001"
    volumes:
      - ./message_service/gateway/cmd:/cmd
    depends_on:
      - message_service_postgres_db
    command: ["./wait-for-it/wait-for-it.sh", "message_service_postgres_db:5432", "-t", "600000000", "--", "/build"]
    restart: on-failure
    networks:
      - "api-network"

  message_service_postgres_db:
    image: postgres:latest
    container_name: message_service_postgres_db
    restart: always
    environment:
      POSTGRES_DB: "friendly_chat_message_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5435:5432"
    volumes:
      - ./message_service/postgres-data:/var/lib/postgresql/data
    networks:
      - "api-network"

  user_service:
    build: "./user_service"
    ports:
      - "10000"
      - "20000"
    volumes:
      - ./user_service/cmd:/cmd
    depends_on:
      - user_service_postgres_db
      - user_service_redis_db
    command: ["./wait-for-it/wait-for-it.sh", "user_service_postgres_db:5432", "user_service_redis_db:6379", "-t", "600000000", "--", "/build"]
    restart: on-failure
    expose:
      - 20000
    networks:
      - "api-network"

  user_service_postgres_db:
    image: postgres:latest
    container_name: user_service_postgres_db
    restart: always
    environment:
      POSTGRES_DB: "friendly_chat_user_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"
    volumes:
      - ./user_service/postgres-data:/var/lib/postgresql/data
    networks:
      - "api-network"

  user_service_redis_db:
    container_name: user_service_redis_db
    image: "redis"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - cache:/data
    networks:
      - "api-network"


volumes:
  cache:
    driver: local

networks:
  api-network: