version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "1000:80"
    depends_on:
      - "push_service"
      - "user_service"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  push_service:
    build: "./push_service"
    ports:
      - "10000"

  user_service:
    build: "./user_service"
    ports:
      - "10000"
