version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "1000:80"
    depends_on:
      - "push_service"
      - "user_service"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  push_service:
    build: "./push_service"
    ports:
      - "10000"
    volumes:
      - ./push_service:/push_service

  message_service_postgres_db:
    image: postgres:latest
    container_name: message_service_postgres_db
    restart: always
    environment:
      POSTGRES_DB: "friendly_chat_message_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5435:5432"
    volumes:
      - ./message_service/postgres-data:/var/lib/postgresql/data


  user_service:
    build: "./user_service"
    ports:
      - "10000"
    volumes:
      - ./user_service/cmd:/cmd
    depends_on:
      - user_service_postgres_db
      - user_service_redis_db
    command: ["./wait-for-it/wait-for-it.sh", "user_service_postgres_db:5432", "user_service_redis_db:6379", "-t", "600000000", "--", "/build"]
    restart: on-failure


  user_service_postgres_db:
    image: postgres:latest
    container_name: user_service_postgres_db
    restart: always
    environment:
      POSTGRES_DB: "friendly_chat_user_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"
    volumes:
      - ./user_service/postgres-data:/var/lib/postgresql/data


  user_service_redis_db:
    container_name: user_service_redis_db
    image: "redis"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

